name: Update PDFs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          lmodern \
          texlive-xetex \
          texlive-latex-recommended \
          texlive-fonts-recommended \
          fonts-dejavu

    - name: Regenerate all documentation
      run: make all

    - name: Commit and push changes if there are any
      run: |
        git add -f pdf/
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update PDFs'
          git push
        else
          echo "No changes to commit"
        fi